### ISSUE TITLE
playwright-assets should be extracted and referenced as a dependency for dev/test

### ISSUE THREAD

**Issue by coreyti** [geometerio/playwright-elixir#10]
Some work has already been done to extract the test assets to [playwright-assets](https://github.com/geometerio/playwright-assets). It would be nice to have that be capable of loading and running as a dependency for this project so that:

- playwright-assets is usable for other projects. These should not necessarily have to be Elixir projects. So, a standalone server is needed.
- playwright-assets is able to be independently updated and version-referenced.
- playwright-elixir is not reported by GitHub to be a project made up mostly of Javascript.

**Comment by woodward** [comment]
maybe we could pattern things after how esbuild is installed in a new Elixir/Phoenix app?

https://github.com/phoenixframework/esbuild

**Comment by dbrody** [comment]
I'm not sure the value in extracting the documents - it will make testing and adding features and pull requests a LOT harder since now two different repos will needs modification in tandem.

The main issue I see is your third point around language statistics. Can you just use something like this instead:
https://github.com/github/linguist/blob/master/docs/overrides.md

Make it independent just for in case of future use to me seems not worth it for the complexity it may add. Just my $0.02.

**Comment by coreyti** [comment]
Thanks for the solution for the language statistics! I had no idea about that, but love the result.

I did decide to go ahead and extract the assets to [playwright-assets](https://github.com/geometerio/playwright-assets). Though you've already provided an exception, @dbrody (with the cookies tests),  I believe it will seldom be the case that developers working on playwright-elixir will need to do much with the assets. The hope/intention is that we'll almost always be able to use the assets from the official Node.js Playwright, and bump those to match versioned releases.

Additionally, being able to run the assets server standalone will make it easier to restore WebSocket transport testing our CI pipeline(s).

**Comment by coreyti** [comment]
Closing for now... happy to discuss further.
