### ISSUE TITLE
Page.query_selector_all test fails intermittently

### ISSUE THREAD

**Issue by sax** [geometerio/playwright-elixir#19]

**Comment by sax** [comment]
@coreyti Erik and I are unable to reproduce this today on my computer. We wondered if there was some specific constraint that we ran into on your computer that might not apply to mine, like RAM.

**Comment by sax** [comment]
I retract my comment. We can reproduce this—it just happens much more rarely on my computer.

**Comment by dbrody** [comment]
@sax Not sure if it is related to this, but I also saw intermitted / more frequent failings of the `query_selector` method too. Adding `%{ strict: false }` option seemed to help. This seems like a new issue in the last few days.

**Comment by sax** [comment]
I filed [this issue](https://github.com/microsoft/playwright/issues/10391) with Playwright, and it seems like this is a known issue unrelated to the Elixir code. We're thinking of implementing locators next, and either adding warnings to the docs or to the compiler for the element handles.

**Comment by coreyti** [comment]
We've added almost all of the `Locator` implementation, which is what the official packages suggest one use instead of `ElementHandle`, `query_selector`, etc.[^1]

We've also removed, for now, async from the running of the test suite. That seems to resolve all of the flakiness pretty well (which is interesting).

[^1]: funnily enough, `Locator` actually depends on `ElementHandle` under the hood.

**Comment by dbrody** [comment]
@coreyti Awesome!

Just a side note, I'm terrible at this too, but I think as this codebase matures, its best to make all changes (perhaps require) through a PR instead of commits on the main branch. That way it can be linked to issues like this so it is references and so that the changes can be reviewed by people like me who depend on the codebase which is quickly changing and evolving.

Anyway, awesome to see the progress and work put into this library!
