### ISSUE TITLE
Has the progress on this just stalled or been abandoned?

### ISSUE THREAD

**Issue by trgoodwin** [geometerio/playwright-elixir#42]

**Comment by coreyti** [comment]
Hi @trgoodwin, thanks for the question and prompt. Progress has stalled at the moment, but the project is certainly not abandoned. I hope to be able to reengage soon, and aim to get more active involvement from our little burgeoning community. I appreciate you checking.

**Comment by coreyti** [comment]
Related:
https://github.com/geometerio/playwright-elixir/issues/44

**Comment by trgoodwin** [comment]
feel free to reach out if you'd like help with moving it forward.

**Comment by bvobart** [comment]
Hi @coreyti, since the last commit on this repo was 5 months ago and I don't see any active branches, I'm hijacking this issue to ask the same question now: what's the current status of this project? Has the progress stalled, been abandoned (even temporarily), deemed enough for your company's use-case, or perhaps superseded / moved? What's still missing in feature parity with Playwright, what's working and what's on the roadmap?
